# Site settings
title: Fream's world
email: fream2016@163.com
description: > # this means to ignore newlines until "baseurl:"
  个人博客。
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://san.sanrabbit.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb

disqus: fream

# Build settings
markdown: rdiscount

permalink: /:year/:month/:day/:title.html
